---
default_stages: [pre-commit, pre-push]


repos:
    - repo: https://github.com/igorshubovych/markdownlint-cli
      rev: v0.38.0 # Use the latest stable version
      hooks:
          - id: markdownlint
            args: [--config, .markdownlint.json]

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3 # or other specific tag
      hooks:
          - id: yamlfmt

    - repo: https://github.com/NixOS/nixfmt
      rev: v1.0.0
      hooks:
          - id: nixfmt
