---
name: CI

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup Nix environment
              uses: aldoborrero/use-nix-action@v4
              with:
                  extra_nix_config: |
                      access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
                  nix_path: nixpkgs=channel:nixos-unstable
            - name: Run pre-commit hooks
              run: pre-commit run --all-files
