---
name: CI

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install Nix
              uses: cachix/install-nix-action@v17
              with:
                  extra_nix_config: |
                      access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            - name: Install direnv with Nix
              uses: aldoborrero/direnv-nix-action@v2
              with:
                  use_nix_profile: true
                  nix_channel: nixpkgs
            - name: Run pre-commit hooks
              run: direnv allow && direnv exec . pre-commit run --all-files
