---
name: CI

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup Nix environment
              uses: aldoborrero/use-nix-action@v4
              with:
                  extra_nix_config: |
                      access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            - name: Add nixpkgs-unstable channel
              run: |
                  nix-channel --add https://nixos.org/channels/nixpkgs-unstable
                  nix-channel --update
            - name: Run pre-commit hooks
              run: pre-commit run --all-files
